### ISSUE TITLE
Selecting the CMA GDC and searching hangs the applications

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#23]
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/8e6080ce-74df-4e7a-ab5b-f52ab56b2f22)

After the selecting the CMA GDC and searching the button keeps spinning and the application is stuck

**Comment by RoryPTB** [comment]
Addressed in PR#35

**Comment by maaikelimper** [comment]
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/e7587f4e-c670-4886-a5ae-15402c95090a)
