### ISSUE TITLE
searching on title does not work 

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#24]
Searching for "Zambia" gives no result:
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/fd5b715e-5167-4a58-babb-1bdaf6ea3332)

If I search in the catalogue on "Zambia" I find a record containing "Zambia" in the title:

![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/6adcd244-b6af-4f09-b938-4abf28195f98)

**Comment by RoryPTB** [comment]
Addressed in PR#36.
