### ISSUE TITLE
update Downloader Server Information section

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#31]
Currently we have:
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/9f4e091a-64ea-40d5-8274-6c780204e0ff)

Replace with 2 text-boxes: Server URL (default=http://localhost:8080) and API-token (default=empty)

**Comment by RoryPTB** [comment]
Addressed by PR#40.
