### ISSUE TITLE
"view JSON" displays JSON error message instead of actual WCMP record in case of missing identifier

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#38]
"view JSON" displays JSON error message instead of actual WCMP record in case of missing identifier

To reproduce do search without input parameter:

Click on "Global Ensemble Prediction Model":
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/5004d18d-e9c1-46c4-9cf5-3976c42b734d)

Click on view json:
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/f50d8ee0-63af-4b13-8740-10259b70de21)

and it displays this as output:
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/87c348ee-a149-4eb9-95b0-4c4516e18884)

**Comment by RoryPTB** [comment]
Addressed by PR#44.
