### ISSUE TITLE
improve display of information in first view of "explore" after search

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#39]
Currently the records displayed when using explore display the Title and a button for "add topic" or "no topic":
![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/fa707e72-bdb4-4649-9fe6-28fbfd762bfd)

The titles are often not  very descriptive (e.g. "Climate stations")".

Suggested updates:

Add:
- dataset creation date
- truncated abstract
- data policy
- earth-system-discipline
- keywords

Add advanced search:
- time-range
- geospatial search
- key words search ?

**Comment by maaikelimper** [comment]
@tomkralidis @amilan17 to provide a minimum set of information to see in the explore page

**Comment by amilan17** [comment]
* full title
* truncated description
* core or recommended "badge"

If listing all data, then also display buttons for data access.

**Comment by tomkralidis** [comment]
Search:
- basic
  - choose GDC
  - text box (triggers `q=` query)
- advanced
  - map widget (draw bounding rectangle)
  - date widget (select start/end date [can be open ended)
Present (brief results):
- Title (`properties.title`)
- Description (truncated `properties.descriptions`)
  - optionally click "More" and display full abstract only in modal)
- "badge" or chiclet of data policy (`properties.wmo:dataPolicy`)
- Country (`properties.contacts[0].addresses[0].country`)
- Earth system discipline (in `properties.themes, find the theme with `scheme=https://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline`, and display the associated `title`)
- Potentially add all access links (but this will become cumbersome/crowded).  Perhaps have an "Access" button that opens a model and enumerates the link objects in HTML
Present (full results):
- full render of WCMP2 record

**Comment by RoryPTB** [comment]
This is addressed mostly by #45 and #52, with the exception of the advanced search. We have agreed today that we should postpone the advanced search until we receive feedback from training sessions and understand precisely what users want.
