### ISSUE TITLE
dataset display in "explore"-tab to mimick pygeoapi-view

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#42]
Instead of:

![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/f0c03b72-cce8-4014-b720-e492520da8d4)

Content should like this:

https://wis2node.bmkg.go.id/oapi/collections/discovery-metadata/items/urn:x-wmo:md:id-bmkg:surface-based-observations.synop

![image](https://github.com/wmo-im/wis2-downloader-gui/assets/19169339/b8a70fa2-924e-4152-aeca-3530a60c9ca5)

**Comment by RoryPTB** [comment]
Addressed by PR #52.
