### ISSUE TITLE
automatically update unit for downloaded volume displayed in "MONITOR"-view

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2-subscription-manager#55]
Rename downloaded bytes with "downloaded data volume" and automatically adjust scale, for example in this screenshot 26,2 kB :
![image](https://github.com/wmo-im/wis2-subscription-manager/assets/19169339/0a6a5023-26f1-4205-9465-5f4c0e320a0b)

**Comment by RoryPTB** [comment]
Addressed in PR #58.
