### ISSUE TITLE
Collect information about data downloaded

### ISSUE THREAD

**Issue by RoryPTB** [wmo-im/wis2-subscription-manager#6]
A database should be implemented into the backend `subscribe_backend.exe` that stores the following information about the downloads:

1. Data ID
2. Data Type (Canonical, Update, Deletion)
3. Topic
4. URL
5. Create Timestamp UTC
6. Update Timestamp UTC (Defaults to create timestamp until there is an update)
7. Status (Success, Failure, Pending)

This data ID should be used to check for duplicates - if the data ID is already found, the data should not be re-downloaded unless the data type is update.

Potential method: TinyDB

**Comment by maaikelimper** [comment]
Can be closed ? The backend now exposes metrics covering most of these

**Comment by RoryPTB** [comment]
Yeah, you're right.
